/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 * @generated by codegen project: GenerateModuleH.js
 */
#include "RNCNetInfoTurboModule.h"
using namespace rnoh;
using namespace facebook;

static jsi::Value __hostFunction_RNCNetInfoTurboModule_configure(jsi::Runtime &rt, react::TurboModule &turboModule, const jsi::Value *args, size_t count)
{
    return static_cast<ArkTSTurboModule &>(turboModule).call(rt, "configure", args, count);
}
static jsi::Value __hostFunction_RNCNetInfoTurboModule_getCurrentState(jsi::Runtime &rt, react::TurboModule &turboModule, const jsi::Value *args, size_t count)
{
    return static_cast<ArkTSTurboModule &>(turboModule).callAsync(rt, "getCurrentState", args, count);
}
static jsi::Value __hostFunction_RNCNetInfoTurboModule_addListener(jsi::Runtime &rt, react::TurboModule &turboModule, const jsi::Value *args, size_t count)
{
    return static_cast<ArkTSTurboModule &>(turboModule).call(rt, "addListener", args, count);
}
static jsi::Value __hostFunction_RNCNetInfoTurboModule_removeListeners(jsi::Runtime &rt, react::TurboModule &turboModule, const jsi::Value *args, size_t count)
{
    return static_cast<ArkTSTurboModule &>(turboModule).call(rt, "removeListeners", args, count);
}
RNCNetInfoTurboModule::RNCNetInfoTurboModule(const ArkTSTurboModule::Context ctx, const std::string name)
    : ArkTSTurboModule(ctx, name)
{
    methodMap_["configure"] = MethodMetadata{0, __hostFunction_RNCNetInfoTurboModule_configure};
    methodMap_["getCurrentState"] = MethodMetadata{0, __hostFunction_RNCNetInfoTurboModule_getCurrentState};
    methodMap_["addListener"] = MethodMetadata{0, __hostFunction_RNCNetInfoTurboModule_addListener};
    methodMap_["removeListeners"] = MethodMetadata{0, __hostFunction_RNCNetInfoTurboModule_removeListeners};
}